# Generated by Django 5.2.8 on 2025-11-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonAn',
            fields=[
                ('maMonAn', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã món ăn')),
                ('tenMonAn', models.CharField(max_length=255, verbose_name='Tên món ăn')),
                ('moTa', models.TextField(verbose_name='Mô tả ngắn')),
                ('chiTiet', models.TextField(verbose_name='Chi tiết (Markdown)')),
                ('thoiGian', models.IntegerField(verbose_name='Thời gian nấu (phút)')),
                ('calo', models.IntegerField(verbose_name='Lượng Calo (kcal)')),
                ('hinhAnh', models.TextField(blank=True, null=True, verbose_name='Đường dẫn hình ảnh')),
                ('loai', models.CharField(choices=[('sang', 'Bữa sáng'), ('trua', 'Bữa trưa'), ('toi', 'Bữa tối')], max_length=100, verbose_name='Loại bữa ăn')),
                ('dsNguyenLieu', models.JSONField(default=list, verbose_name='Danh sách ID nguyên liệu')),
                ('dsNguyenLieu_hash', models.CharField(blank=True, max_length=64, null=True, verbose_name='Hash nguyên liệu')),
            ],
            options={
                'verbose_name': 'Món Ăn',
                'verbose_name_plural': 'Danh sách Món Ăn',
            },
        ),
    ]
