# Generated by Django 5.2.8 on 2025-12-03 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NguyenLieu',
            fields=[
                ('maNguyenLieu', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã nguyên liệu')),
                ('tenNguyenLieu', models.CharField(max_length=200, unique=True, verbose_name='Tên nguyên liệu')),
            ],
            options={
                'verbose_name': 'Nguyên Liệu (Tags)',
                'verbose_name_plural': 'Danh sách Nguyên Liệu',
            },
        ),
        migrations.CreateModel(
            name='MonAn',
            fields=[
                ('maMonAn', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã món ăn')),
                ('tenMonAn', models.CharField(max_length=255, verbose_name='Tên món ăn')),
                ('moTa', models.TextField(verbose_name='Mô tả ngắn')),
                ('chiTiet', models.TextField(verbose_name='Chi tiết công thức (Markdown)')),
                ('thoiGian', models.IntegerField(verbose_name='Thời gian nấu (phút)')),
                ('calo', models.IntegerField(verbose_name='Lượng Calo (kcal)')),
                ('hinhAnh', models.ImageField(blank=True, null=True, upload_to='monan/', verbose_name='Ảnh món ăn')),
                ('loai', models.CharField(choices=[('sang', 'Bữa sáng'), ('trua', 'Bữa trưa'), ('toi', 'Bữa tối')], max_length=100, verbose_name='Loại bữa ăn')),
                ('nguyen_lieu', models.ManyToManyField(blank=True, related_name='cac_mon_an', to='smartchef_core.nguyenlieu', verbose_name='Chọn nguyên liệu liên quan')),
            ],
            options={
                'verbose_name': 'Món Ăn',
                'verbose_name_plural': 'Danh sách Món Ăn',
            },
        ),
    ]
