# Generated by Django 5.2.8 on 2025-11-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartchef_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monan',
            name='hinhAnh',
            field=models.ImageField(blank=True, null=True, upload_to='monan/', verbose_name='Ảnh món ăn'),
        ),
    ]
