# Generated by Django 5.2.8 on 2025-12-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartchef_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monan',
            name='nguyen_lieu',
            field=models.ManyToManyField(blank=True, related_name='cac_mon_an', to='smartchef_core.nguyenlieu', verbose_name='Chọn nguyên liệu'),
        ),
    ]
