# Generated by Django 5.2.8 on 2025-12-06 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartchef_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='monan',
            name='nguyen_lieu',
            field=models.ManyToManyField(blank=True, related_name='cac_mon_an', to='smartchef_core.nguyenlieu', verbose_name='Chọn nguyên liệu'),
        ),
        migrations.CreateModel(
            name='YeuThich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True)),
                ('mon_an', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartchef_core.monan', verbose_name='Món ăn')),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Lượt Yêu Thích',
                'verbose_name_plural': 'Danh sách Yêu Thích',
                'unique_together': {('nguoi_dung', 'mon_an')},
            },
        ),
    ]
