# Generated by Django 5.2.8 on 2025-12-06 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartchef_core', '0002_alter_monan_nguyen_lieu_yeuthich'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yeuthich',
            name='mon_an',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yeuthich', to='smartchef_core.monan', verbose_name='Món ăn'),
        ),
    ]
